<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastComments($limit)
    {
        return $this->createQueryBuilder('comment')
            ->select('comment, post')
            ->leftJoin('comment.post', 'post')
            ->setMaxResults($limit)
            ->orderBy('comment.id', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }

}
