<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllQuery()
    {
        return $this->createQueryBuilder('post')
                ->getQuery();
    }

    public function findByTagQuery($name)
    {
        return $this->createQueryBuilder('post')
            ->select('post, tag')
            ->leftJoin('post.tags', 'tag')
            ->andWhere('tag.name = :name')
            ->setParameter('name', $name)
            ->getQuery()
            ;
    }

    public function findByQueryQuery($query)
    {
        return $this->createQueryBuilder('post')
            ->select('post, tag')
            ->leftJoin('post.tags', 'tag')
            ->orWhere('tag.name = :q')
            ->orWhere("post.pagetitle LIKE '%$query%'")
            ->orWhere("post.content LIKE '%$query%'")
            ->setParameter('q', $query)
            ->getQuery()
            ;
    }

    /**
     * @param $slug
     * @return Post
     */
    public function findBySlug($slug)
    {
        return $this->createQueryBuilder('p')
            ->select('p, avg(c.rating) as avg_rating')
            ->leftJoin('p.tags', 't')
            ->Join('p.comments', 'c')
            ->andWhere('p.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
