<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findUserByNameAndRole($name ,$role)
    {
        return $this->createQueryBuilder('user')
            ->andWhere('user.username = :name')
            ->andWhere('user.roles LIKE :roles')
            ->setParameter('name', $name)
            ->setParameter('roles', '%"'.$role.'"%')
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }

}
