# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    app.twig_extension:
#        class: AppBundle\Twig\AppExtension
#        public: false
#        arguments:
#          doctrine: "@doctrine"
#        tags:
#            - { name: twig.extension }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.security.role_hierarchy_checker:
        class: AppBundle\Security\RoleHierarchyChecker
        arguments: [@security.role_hierarchy]

    app.comment_voter:
        class: AppBundle\Security\CommentVoter
        arguments: [@security.access.decision_manager, @app.security.role_hierarchy_checker]
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
